name: mind_cove
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  calendar_date_picker2: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  image_picker: ^1.1.2
  path_provider: ^2.1.2
  crypto: ^3.0.6
  path: ^1.9.1
  provider: ^6.1.5
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true
